INSERT INTO movie(title,  id) VALUES
('The Shawshank Redemption', 1),
('The Godfather', 2),
('The Godfather: Part II', 3),
('Pulp Fiction', 4),
('The Good\, the Bad and the Ugly', 5),
('The Dark Knight', 6),
('12 Angry Men', 7),
('Schindler''s List', 8),
('The Lord of the Rings: The Return of the King', 9),
('Fight Club', 10),
('Star Wars: Episode V - The Empire Strikes Back', 11),
('The Lord of the Rings: The Fellowship of the Ring', 12),
('One Flew Over the Cuckoo''s Nest',  13),
('Inception', 14),
('Goodfellas', 15),
('Star Wars', 16),
('Seven Samurai', 17),
('Forrest Gump', 18),
('The Matrix', 19),
('The Lord of the Rings: The Two Towers', 20),
('City of God', 21),
('Se7en', 22),
('The Silence of the Lambs', 23),
('Once Upon a Time in the West', 24),
('Casablanca', 25),
('The Usual Suspects', 26),
('Raiders of the Lost Ark', 27),
('Rear Window', 28),
('It''s a Wonderful Life', 29),
('Psycho', 30),
('Léon: The Professional', 31),
('Sunset Blvd.', 32),
('American History X', 33),
('Apocalypse Now', 34),
('Terminator 2: Judgment Day', 35),
('Saving Private Ryan', 36),
('Memento', 37),
('City Lights', 38),
('Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', 39),
('Alien', 40),
('Modern Times', 41),
('Spirited Away', 42),
('North by Northwest', 43),
('Back to the Future', 44),
('Life Is Beautiful', 45),
('The Shining', 46),
('The Pianist', 47),
('Citizen Kane', 48),
('The Departed', 49),
('M', 50),
('Paths of Glory', 51),
('Vertigo', 52),
('Django Unchained', 53),
('Double Indemnity', 54),
('The Dark Knight Rises', 55),
('Aliens', 56),
('Taxi Driver', 57),
('American Beauty', 58),
('The Green Mile', 59),
('Gladiator', 60),
('The Intouchables', 61),
('WALL·E', 62),
('The Lives of Others', 63),
('Toy Story 3', 64),
('The Great Dictator', 65),
('The Prestige', 66),
('A Clockwork Orange', 67),
('Lawrence of Arabia', 68),
('Amélie', 69),
('To Kill a Mockingbird', 70),
('Reservoir Dogs', 71),
('Das Boot', 72),
('The Lion King', 73),
('Cinema Paradiso', 74),
('Star Wars: Episode VI - Return of the Jedi', 75),
('The Treasure of the Sierra Madre', 76),
('The Third Man', 77),
('Once Upon a Time in America', 78),
('Requiem for a Dream', 79),
('Eternal Sunshine of the Spotless Mind', 80),
('Full Metal Jacket', 81),
('Oldboy', 82),
('Braveheart', 83),
('L.A. Confidential', 84),
('Bicycle Thieves', 85),
('Chinatown', 86),
('Singin'' in the Rain', 87),
('Princess Mononoke', 88),
('Monty Python and the Holy Grail', 89),
('Metropolis', 90),
('Rashomon', 91),
('Some Like It Hot', 92),
('Amadeus', 93),
('2001: A Space Odyssey', 94),
('All About Eve', 95),
('Witness for the Prosecution', 96),
('The Sting', 97),
('The Apartment', 98),
('Grave of the Fireflies', 99),
('Indiana Jones and the Last Crusade', 100);